### ISSUE TITLE
bma crashed server   smash hammer

### ISSUE THREAD

**Issue by Gromyown** [ArtixAllMighty/Rpg-Addon-BerserkMageArcher#4]
[09:51:10] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) ~[nx.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at subaraki.BMA.entity.EntityHammerSmash.func_70071_h_(EntityHammerSmash.java:142) ~[EntityHammerSmash.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1976) ~[ams.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833) ~[om.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1939) ~[ams.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1753) ~[ams.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614) ~[om.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761) ~[MinecraftServer.class:?]
	... 4 more
[09:51:10] [Server thread/ERROR]: This crash report has been saved to: G:\Working Forge Minecraft Server\.\crash-reports\crash-2017-08-08_09.51.10-server.txt

**Comment by Gromyown** [comment]
ok  i  pulled the sorce from git but im having no luck creating it i 
managed to get it to compile once  but i did something wronge and had no 
spells in the magic book    i didnt know what to run first  the 
construct or the build bats so i ran them both but it did not make a jar 
and if it did i cant find it lmfao

**Comment by ArtixAllMighty** [comment]
oops. did i not update the mod yet ?

**Comment by ArtixAllMighty** [comment]
there. now its updated =) 
sorry for the delay !! 
https://minecraft.curseforge.com/projects/class-armor-berserker-mage-and-archer/files/2468995

**Comment by JuicebQx** [comment]
Hey, just thought I'd let you know that the hammer crashes me and my friend's game and even possibly the server on occasion when we use the smash feature in the latest version of minecraft
